// @ts-nocheck
import express from 'express'; import cors from 'cors'; import jwt from 'jsonwebtoken'; import bcrypt from 'bcryptjs'; import path from 'node:path'; import {PrismaClient,Role,EventStatus,RegistrationStatus,Prisma} from '@prisma/client'; import {z} from 'zod';
const app=express(), prisma=new PrismaClient(), secret=process.env.JWT_SECRET||'campusly-development-secret'; if(process.env.NODE_ENV!=='production')app.use(cors());app.use(express.json());
const distPath=path.resolve(process.cwd(),'dist'); app.use(express.static(distPath));
type Req=express.Request&{user?:any}; const route=(fn:any)=>(req:any,res:any,next:any)=>Promise.resolve(fn(req,res,next)).catch(next); const auth=route(async(req:Req,res:any,next:any)=>{const raw=req.headers.authorization?.replace('Bearer ','');if(!raw)return res.status(401).json({error:'Authentication required.'});try{req.user=jwt.verify(raw,secret);next()}catch{res.status(401).json({error:'Session expired. Please sign in again.'})}});const admin=(req:Req,res:any,next:any)=>req.user?.role===Role.ADMIN?next():res.status(403).json({error:'Admin access required.'});const token=(u:any)=>jwt.sign({id:u.id,name:u.name,email:u.email,role:u.role},secret,{expiresIn:'7d'});
const eventSchema=z.object({title:z.string().trim().min(3),description:z.string().trim().min(10),category:z.string().min(2),date:z.coerce.date(),startTime:z.string().regex(/^\d{2}:\d{2}$/),endTime:z.string().regex(/^\d{2}:\d{2}$/),venue:z.string().trim().min(2),organizer:z.string().trim().min(2),capacity:z.coerce.number().int().positive(),image:z.string().url(),status:z.enum(['UPCOMING','COMPLETED','CANCELLED']).optional()});const select={id:true,title:true,description:true,category:true,date:true,startTime:true,endTime:true,venue:true,organizer:true,capacity:true,image:true,status:true,createdAt:true,updatedAt:true} as const;
app.get('/api/health',route(async(_req,res)=>{await prisma.$queryRaw`SELECT 1`;res.json({status:'ok'})}));
app.post('/api/auth/register',route(async(req,res)=>{const p=z.object({name:z.string().trim().min(2),email:z.string().email().transform(v=>v.toLowerCase()),password:z.string().min(6)}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Enter a valid name, email, and password.'});if(await prisma.user.findUnique({where:{email:p.data.email}}))return res.status(409).json({error:'An account with this email already exists.'});const u=await prisma.user.create({data:{name:p.data.name,email:p.data.email,passwordHash:await bcrypt.hash(p.data.password,12)}});res.status(201).json({token:token(u),user:{id:u.id,name:u.name,email:u.email,role:u.role}})}));
app.post('/api/auth/login',route(async(req,res)=>{const p=z.object({email:z.string().email(),password:z.string()}).safeParse(req.body);const u=p.success?await prisma.user.findUnique({where:{email:p.data.email.toLowerCase()}}):null;if(!p.success||!u||!(await bcrypt.compare(p.data.password,u.passwordHash)))return res.status(401).json({error:'Email or password is incorrect.'});res.json({token:token(u),user:{id:u.id,name:u.name,email:u.email,role:u.role}})}));app.get('/api/auth/me',auth,route(async(req:Req,res)=>res.json(req.user)));app.post('/api/auth/logout',auth,(_req,res)=>res.status(204).end());
app.get('/api/events',route(async(req,res)=>{const q=String(req.query.q||'').trim(),category=String(req.query.category||'All');res.json(await prisma.event.findMany({where:{...(category!=='All'?{category}:{}),...(q?{OR:[{title:{contains:q,mode:'insensitive'}},{description:{contains:q,mode:'insensitive'}},{venue:{contains:q,mode:'insensitive'}}]}:{})},select,orderBy:{date:'asc'}}))}));app.get('/api/events/:id',route(async(req,res)=>{const e=await prisma.event.findUnique({where:{id:req.params.id},select});e?res.json(e):res.status(404).json({error:'Event not found.'})}));
app.post('/api/events/:id/register',auth,route(async(req:Req,res)=>{const e=await prisma.event.findUnique({where:{id:req.params.id}});if(!e)return res.status(404).json({error:'Event not found.'});if(e.status!==EventStatus.UPCOMING)return res.status(400).json({error:'Registration is closed for this event.'});if(await prisma.registration.count({where:{eventId:e.id,status:RegistrationStatus.CONFIRMED}})>=e.capacity)return res.status(409).json({error:'This event is full.'});try{res.status(201).json(await prisma.registration.create({data:{eventId:e.id,userId:req.user.id},include:{event:{select}}}))}catch(e){if(e instanceof Prisma.PrismaClientKnownRequestError&&e.code==='P2002')return res.status(409).json({error:'You are already registered for this event.'});throw e}}));
app.delete('/api/events/:id/register',auth,route(async(req:Req,res)=>{const r=await prisma.registration.findFirst({where:{eventId:req.params.id,userId:req.user.id,status:RegistrationStatus.CONFIRMED}});if(!r)return res.status(404).json({error:'Registration not found.'});res.json(await prisma.registration.update({where:{id:r.id},data:{status:RegistrationStatus.CANCELLED}}))}));app.get('/api/users/me/registrations',auth,route(async(req:Req,res)=>res.json(await prisma.registration.findMany({where:{userId:req.user.id},include:{event:{select}},orderBy:{registeredAt:'desc'}}))));
app.get('/api/admin/analytics',auth,admin,route(async(req,res)=>{const [events,registrations,upcoming,capacity]=await Promise.all([prisma.event.count(),prisma.registration.count(),prisma.event.count({where:{status:EventStatus.UPCOMING}}),prisma.event.aggregate({_sum:{capacity:true}})]);res.json({events,registrations,upcoming,capacity:capacity._sum.capacity||0})}));app.get('/api/admin/events',auth,admin,route(async(req,res)=>res.json(await prisma.event.findMany({select,orderBy:{date:'asc'}}))));
app.post('/api/events',auth,admin,route(async(req,res)=>{const p=eventSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'Please complete all event fields with valid values.'});res.status(201).json(await prisma.event.create({data:{...p.data,status:(p.data.status as EventStatus)||EventStatus.UPCOMING},select}))}));app.put('/api/events/:id',auth,admin,route(async(req,res)=>{const p=eventSchema.partial().safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid event data.'});try{res.json(await prisma.event.update({where:{id:req.params.id},data:p.data as any,select}))}catch(e){if(e instanceof Prisma.PrismaClientKnownRequestError&&e.code==='P2025')return res.status(404).json({error:'Event not found.'});throw e}}));app.delete('/api/events/:id',auth,admin,route(async(req,res)=>{try{await prisma.event.delete({where:{id:req.params.id}});res.status(204).end()}catch(e){if(e instanceof Prisma.PrismaClientKnownRequestError&&e.code==='P2025')return res.status(404).json({error:'Event not found.'});throw e}}));app.patch('/api/admin/events/:id/status',auth,admin,route(async(req,res)=>{const p=z.object({status:z.enum(['UPCOMING','COMPLETED','CANCELLED'])}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid event status.'});res.json(await prisma.event.update({where:{id:req.params.id},data:{status:p.data.status as EventStatus},select}))}));app.get('/api/admin/events/:id/participants',auth,admin,route(async(req,res)=>res.json(await prisma.registration.findMany({where:{eventId:req.params.id},include:{user:{select:{id:true,name:true,email:true,role:true}}}}))));
app.use((req,res,next)=>{if(req.method==='GET'&&!req.path.startsWith('/api'))return res.sendFile(path.join(distPath,'index.html'));next()});app.use((err:any,_req:any,res:any,_next:any)=>{if(process.env.NODE_ENV!=='production')console.error(err);res.status(500).json({error:'Something went wrong on the server.'})});app.listen(Number(process.env.PORT||4000),()=>console.log(`Campusly API listening on port ${process.env.PORT||4000}`));
